// <auto-generated />
namespace MojCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mar24Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mar24Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241501398_Mar24Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
