// <auto-generated />
namespace MojCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jul13UpdateLeads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jul13UpdateLeads));
        
        string IMigrationMetadata.Id
        {
            get { return "201707131828531_Jul13UpdateLeads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
