// <auto-generated />
namespace MojCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Feb17Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feb17Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201702171820523_Feb17Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
