// <auto-generated />
namespace MojCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jul11Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jul11Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111556344_Jul11Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
